#!/usr/bin/python3

import sys
import random
import time


def is_prime(arg, k=20):
    '''
    '''
    if arg == 2 or arg == 3:
        return True
    if arg < 2 or arg % 2 == 0:
        return False


    d = arg - 1
    r = 0
    while d % 2 == 0:
        d //= 2
        r += 1


    for _ in range(k):
        a = random.randint(2, arg - 2)
        x = pow(a, d, arg)
        if x == 1 or x == arg - 1:
            continue
        for _ in range(r - 1):
            x = pow(x, 2, arg)
            if x == arg - 1:
                break
        else:
            return False


    return True


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        exit()


    called_file = sys.argv[1]
    
    try:
        with open(called_file, "r") as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()


    s_time = time.time()

    number = int(lines[0].strip())
    for i in range(2, number//2):
        if number % i == 0 and is_prime(i) and is_prime(number//i):
            print("{}={}*{}".format(number, number//i, i))
            break


        if time.time() - s_time > 5:
            print("Time limit exceeded")
            exit()
