#!/usr/bin/python3

import sys
import time
from math import sqrt, ceil


def is_prime(arg):
    if arg < 2:
        return False
    for num in range(2, int(sqrt(arg)) + 1):
        if arg % num == 0:
            return False
    return True


def factor_rsa_number(num):
    factors = []

    while num % 2 == 0:
        factors.append(2)
        num //= 2

    val = 3
    while val <= sqrt(num):
        if num % val == 0:
            factors.append(val)
            num //= val
        else:
            val += 2

    if num > 2:
        factors.append(num)

    if len(factors) == 1:
        x = factors[0]
        y = num // x
        return (x, y)

    else:
        pq = []
        for factor in factors:
            if is_prime(factor):
                pq.append(factor)
            else:
                x, y = factor_rsa_number(factor)
                pq.append(x)
                pq.append(y)
        return tuple(pq)


_file = sys.argv[1]


with open(_file, 'r') as f:
    rsa_numbers = [int(line.strip()) for line in f.readlines()]

s_time = time.time()


for n in rsa_numbers:
    x, y = factor_rsa_number(n)
    print("{}={}*{}".format(n, y, x))


# Stop the timer and calculate the execution time
e_time = time.time()
exec_time = e_time - s_time


# Print the execution time in seconds
# print("Total execution time: ", exec_time, " seconds")
